# Site settings
title: Jigsaw Payment
SEOTitle: Jigsaw Payment | 聚合支付
header-img: img/home-bg.jpg
email: shamphone@gmail.com
description: "Jigsaw Payment，一个使用微服务来构建的聚合支付系统"
keyword: "Jigsaw Payment， 聚合支付，微服务"
url: "https://blog.lixf.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
encoding: UTF-8


# SNS settings
# RSS: false
# weibo_username:     shamphone
# zhihu_username:     shamphone
# github_username:    shamphone
# twitter_username:  shamphone
# facebook_username:  shamphone
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_


# Analytics settings
# Baidu Analytics
ba_track_id: 7590b8f08665741fdf5a4d378feccaaf
# Google Analytics
# ga_track_id: 'UA-82322518-1'            # Format: UA-xxxxxx-xx
# ga_domain: jigsaw.lixf.cn



# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "开源聚合支付"
sidebar-avatar: /img/avatar-lixf.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
#friends: [
#    {
#        title: "Su",
#        href: "http://su.gallery/"
#    },{
#        title: "乱序",
#        href: "http://mida.re/"
#    },{
#        title: "前端外刊评论",
#        href: "http://qianduan.guru/"
#    }
#]
